# Generated by Django 4.2.7 on 2026-02-26 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(default='#808080', help_text='Cor em hexadecimal (ex: #FF0000)', max_length=7)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_personalizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('user', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(blank=True, max_length=300, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30, null=True)),
                ('site', models.URLField(blank=True, max_length=255, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('proprietarios', models.ManyToManyField(related_name='leads_adquiridos', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.statuspersonalizado')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoBusca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_empresa', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=2)),
                ('data_busca', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_buscas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_busca'],
                'unique_together': {('user', 'tipo_empresa', 'cidade', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('mensagem_padrao', models.TextField(blank=True, help_text='Mensagem padrão para ser enviada aos leads desta campanha.', null=True)),
                ('leads', models.ManyToManyField(related_name='campanhas', to='leads.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
                'unique_together': {('user', 'nome')},
            },
        ),
    ]
