# Generated by Django 4.2.7 on 2026-02-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Qualificado', 'Qualificado'), ('Verificado', 'Verificado'), ('Contatado', 'Contatado'), ('Respondido', 'Respondido'), ('Negociando', 'Em Negociação'), ('Ganhamos', 'Ganhamos'), ('Perdemos', 'Perdemos'), ('Telefone Inexistente', 'Telefone Inexistente')], default='Qualificado', max_length=30),
        ),
        migrations.DeleteModel(
            name='StatusPersonalizado',
        ),
    ]
