# Generated by Django 4.2.7 on 2026-06-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_templatemensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='anexo',
            field=models.FileField(blank=True, help_text='Arquivo (ex: catálogo em PDF) enviado junto com a mensagem.', null=True, upload_to='anexos_campanhas/'),
        ),
    ]
