# Generated by Django 4.2.7 on 2026-07-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_campanha_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='hashtags_finais',
            field=models.TextField(blank=True, help_text='Opções de hashtag para adicionar ao final da mensagem, uma por linha. Uma delas é escolhida aleatoriamente a cada envio.', null=True),
        ),
    ]
