# Generated by Django 4.2.7 on 2026-08-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_campanha_hashtags_finais'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoDisparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloqueado', models.BooleanField(default=False, help_text='Se marcado, nenhum usuário consegue iniciar disparos de campanha.')),
                ('mensagem_bloqueio', models.TextField(default='Disparos de campanha temporariamente pausados para manutenção do sistema. Tente novamente mais tarde.', help_text='Mensagem exibida ao usuário quando ele tentar disparar uma campanha com a trava ativa.')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Disparo',
                'verbose_name_plural': 'Configuração de Disparo',
            },
        ),
    ]
