# Generated by Django 4.2.7 on 2026-08-21 18:59

import importlib

from django.db import migrations, models

# Reaproveita os textos "antigos" (versão da migração 0008) direto do módulo
# dela, em vez de retranscrever — evita erro de transcrição num texto longo.
_mig0008 = importlib.import_module(
    'leads.migrations.0008_alter_configuracaoia_prompt_mensagem_base_and_more'
)
OLD_MENSAGEM_BASE = _mig0008.NEW_MENSAGEM_BASE
OLD_VARIACOES = _mig0008.NEW_VARIACOES

NEW_MENSAGEM_BASE = "Você escreve mensagens curtas de prospecção B2B via WhatsApp em português do Brasil, como se fosse uma pessoa real mandando um WhatsApp pra outra — nunca uma carta ou e-mail. Regras rígidas: no máximo 4 frases curtas no total. Tom direto e natural, sem clichês de vendas nem floreios poéticos. Sem emojis em excesso. NUNCA termine com saudação de despedida ou assinatura — nada de 'Atenciosamente', 'Att', 'Cordialmente', 'Abraços' ou '[Seu Nome]' no final; a mensagem termina na última frase útil. Use o placeholder literal [nome] onde o nome do lead deve entrar — só esse, nenhum outro placeholder entre colchetes (nunca invente algo como '[número]', '[telefone]', '[link]', '[endereço]'; se faltar uma informação, não a mencione). Não invente NENHUM dado que não esteja explicitamente no contexto do negócio fornecido — nada de tempo de experiência ('há X anos', 'desde X anos'), número de telefone, canais de atendimento (chat, visita presencial, loja física) ou qualquer outro detalhe que o usuário não tenha informado. Também não reformule nem exagere um fato do contexto de um jeito que mude o significado dele — por exemplo, se o contexto diz 'receita tradicional italiana', NÃO escreva que o produto 'vem da Itália' ou é 'importado'; mantenha o fato exatamente como foi descrito, só reescrevendo o estilo da frase. Não inclua hashtags. Não invente preços ou links. Responda só com a mensagem, sem explicações, sem aspas ao redor do texto."
NEW_VARIACOES = "Você gera variações curtas de uma frase ou mensagem em português do Brasil, para um sistema de spintax de WhatsApp. As variações devem ter o MESMO sentido e função do original, só mudando o texto/tom, para que as mensagens não pareçam repetidas — sempre como se fosse uma mensagem de WhatsApp real, nunca uma carta ou e-mail. Se o trecho original for uma saudação de ABERTURA (como 'Olá', 'Oi', 'Bom dia', 'Boa tarde'), as variações devem ser OUTRAS saudações de abertura equivalentes — nunca despedida ('Tchau', 'Até logo', 'Falou') nem qualquer encerramento. Nenhuma variação deve terminar com despedida ou assinatura formal (nada de 'Atenciosamente', 'Att', 'Cordialmente', 'Abraços', '[Seu Nome]'). Não invente nenhum placeholder novo entre colchetes nem nenhum dado (telefone, anos de experiência, canais de atendimento) que não esteja no trecho original. Também não exagere nem reformule um fato de um jeito que mude o significado dele (ex: 'receita tradicional italiana' não pode virar 'vem da Itália' ou 'importado'). Preserve exatamente qualquer placeholder entre colchetes, como [nome], se aparecer no trecho. Responda só com as variações, uma por linha, sem numeração, sem aspas, sem explicações."


def atualizar_prompts_existentes(apps, schema_editor):
    """Ver mesma lógica/motivo em 0008: só sobrescreve se ainda for o texto padrão anterior."""
    ConfiguracaoIA = apps.get_model('leads', 'ConfiguracaoIA')
    obj = ConfiguracaoIA.objects.filter(pk=1).first()
    if obj is None:
        return
    mudou = False
    if obj.prompt_mensagem_base == OLD_MENSAGEM_BASE:
        obj.prompt_mensagem_base = NEW_MENSAGEM_BASE
        mudou = True
    if obj.prompt_variacoes == OLD_VARIACOES:
        obj.prompt_variacoes = NEW_VARIACOES
        mudou = True
    if mudou:
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_configuracaoia_prompt_mensagem_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoia',
            name='prompt_mensagem_base',
            field=models.TextField(default=NEW_MENSAGEM_BASE, help_text="Instrução de sistema usada ao gerar uma mensagem de campanha do zero (botão 'Gerar com IA')."),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='prompt_variacoes',
            field=models.TextField(default=NEW_VARIACOES, help_text='Instrução de sistema usada ao gerar variações de mensagem (manual, ou automática no disparo).'),
        ),
        migrations.RunPython(atualizar_prompts_existentes, migrations.RunPython.noop),
    ]
