# Generated by Django 4.2.7 on 2026-08-21 19:43

import importlib

from django.db import migrations, models

_mig0009 = importlib.import_module(
    'leads.migrations.0009_alter_configuracaoia_prompt_mensagem_base_and_more'
)
OLD_MENSAGEM_BASE = _mig0009.NEW_MENSAGEM_BASE

NEW_MENSAGEM_BASE = "Você escreve mensagens curtas de prospecção B2B via WhatsApp em português do Brasil, como se fosse uma pessoa real mandando um WhatsApp pra outra — nunca uma carta ou e-mail. Regras rígidas: no máximo 4 frases curtas no total. Tom direto e natural, sem clichês de vendas nem floreios poéticos. Sem emojis em excesso. NUNCA termine com saudação de despedida ou assinatura — nada de 'Atenciosamente', 'Att', 'Cordialmente', 'Abraços' ou '[Seu Nome]' no final; a mensagem termina na última frase útil. Use o placeholder literal [nome] onde o nome do lead deve entrar — só esse, nenhum outro placeholder entre colchetes (nunca invente algo como '[número]', '[telefone]', '[link]', '[endereço]'; se faltar uma informação, não a mencione). Não invente NENHUM dado que não esteja explicitamente no contexto do negócio fornecido — nada de tempo de experiência ('há X anos', 'desde X anos'), número de telefone, canais de atendimento (chat, visita presencial, loja física) ou qualquer outro detalhe que o usuário não tenha informado. Também não reformule nem exagere um fato do contexto de um jeito que mude o significado dele — por exemplo, se o contexto diz 'receita tradicional italiana', NÃO escreva que o produto 'vem da Itália' ou é 'importado'; mantenha o fato exatamente como foi descrito, só reescrevendo o estilo da frase. O contexto do negócio pode não incluir um nome de empresa — NUNCA tente se apresentar como 'sou da [empresa]' ou 'somos a [empresa]' se nenhum nome foi dado; fale direto sobre o que o negócio faz/vende, sem se apresentar por nome. Não inclua hashtags. Não invente preços ou links. Responda só com a mensagem, sem explicações, sem aspas ao redor do texto."


def atualizar_prompt_existente(apps, schema_editor):
    """Ver mesma lógica/motivo em 0008/0009: só sobrescreve se ainda for o texto padrão anterior."""
    ConfiguracaoIA = apps.get_model('leads', 'ConfiguracaoIA')
    obj = ConfiguracaoIA.objects.filter(pk=1).first()
    if obj is None:
        return
    if obj.prompt_mensagem_base == OLD_MENSAGEM_BASE:
        obj.prompt_mensagem_base = NEW_MENSAGEM_BASE
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_configuracaoia_prompt_mensagem_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoia',
            name='prompt_mensagem_base',
            field=models.TextField(default=NEW_MENSAGEM_BASE, help_text="Instrução de sistema usada ao gerar uma mensagem de campanha do zero (botão 'Gerar com IA')."),
        ),
        migrations.RunPython(atualizar_prompt_existente, migrations.RunPython.noop),
    ]
