# Generated by Django 4.2.7 on 2026-03-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='creditos_disponiveis',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='total_extraido',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='limite_leads',
            field=models.PositiveIntegerField(default=50, help_text='Número máximo de leads que o usuário pode ter em seu banco.'),
        ),
    ]
