# Generated by Django 4.2.7 on 2026-02-28 20:00

from django.db import migrations

def criar_planos_iniciais(apps, schema_editor):
    """
    Cria os planos Starter e Pro no banco de dados.
    """
    Plano = apps.get_model('accounts', 'Plano')
    
    planos_a_criar = [
        {'nome': 'Starter', 'limite_leads': 50, 'preco': 28.90, 'ciclo_meses': 1, 'ativo': True},
        {'nome': 'Pro', 'limite_leads': 100, 'preco': 34.95, 'ciclo_meses': 1, 'ativo': True},
    ]

    for plano_data in planos_a_criar:
        # Usa get_or_create para evitar duplicatas se a migração for rodada novamente
        Plano.objects.get_or_create(
            nome=plano_data['nome'],
            defaults=plano_data
        )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_plano_perfilusuario_plano'),
    ]

    operations = [
        migrations.RunPython(criar_planos_iniciais),
    ]
