# Generated by Django 4.2.7 on 2026-04-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_popular_planos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='limite_leads',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='plano',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='creditos_disponiveis',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='plano_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='total_extraido',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Plano',
        ),
    ]
