# Generated by Django 4.2.7 on 2026-07-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_perfilusuario_stripe_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='creditos_disponiveis',
            field=models.IntegerField(default=1),
        ),
    ]
