# Generated by Django 4.2.7 on 2026-07-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_perfilusuario_creditos_disponiveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappinstance',
            name='enviando_campanha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='envios_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='envios_hoje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='limite_diario_envios',
            field=models.IntegerField(default=40),
        ),
    ]
