# Generated by Django 4.2.7 on 2026-07-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_whatsappinstance_enviando_campanha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappinstance',
            name='disparo_iniciado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
