# Generated by Django 4.2.7 on 2026-08-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_whatsappinstance_disparo_iniciado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='contexto_negocio',
            field=models.TextField(blank=True, help_text='Breve descrição do negócio do usuário, usada como contexto para a IA gerar mensagens.', null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ia_geracoes_usadas_mes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ia_mes_referencia',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
