# Generated by Django 4.2.7 on 2026-08-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_perfilusuario_contexto_negocio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappinstance',
            name='cancelar_disparo',
            field=models.BooleanField(default=False),
        ),
    ]
